# Generated by Django 2.1.7 on 2019-09-16 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('session_code', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Book_Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biblioteca.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('devolution_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_registration', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('adress', models.TextField(max_length=200)),
                ('tel', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='user_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biblioteca.User'),
        ),
        migrations.AddField(
            model_name='book_loan',
            name='loan_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='biblioteca.Loan'),
        ),
    ]
